version: '3.2'
services:
  nginx:
    container_name: nginx
    image: nginx:1.20.2-alpine
    ports:
      - 80:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./workspace:/var/www/html
    links:
      - php
  php:
    container_name: php
    image: getjv/php-fpm
    volumes:
      - ./workspace:/var/www/html
